spring.application.name=user-service

app.jwt.private-key-location=classpath:certs/private.pem
app.jwt.public-key-location=classpath:certs/public.pem
app.jwt.issuer=user-service
app.jwt.access-token-ttl=15m
app.jwt.refresh-token-ttl=30d
